# -*- coding: utf-8 -*-
"""Christmas21.ipynb

Automatically generated by Colab.

# Option Pricing with Historical Data Monte Carlo in Pyspark

# Utils

## Load Packages
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install pyspark

!pip install yfinance

import yfinance as yf
import datetime
import time
import requests
import io

from pyspark.sql import SparkSession, SQLContext
from pyspark import SparkContext,SparkConf

# Commented out IPython magic to ensure Python compatibility.
from os.path import expanduser, join, abspath
from pyspark.sql import Row
from pyspark.sql import functions as F
from pyspark.sql import Window
import collections
import pandas as pd
import numpy as np
# %matplotlib inline
import matplotlib.pyplot as plt
from pyspark.sql.functions import *

from pyspark.sql.types import StructType, StructField, IntegerType, StringType, FloatType, DoubleType

"""## Data Load and Preprocess"""

def GetYFinanceData (x):
    data = yf.download(x, period = 'max')
    S0=data.iloc[len(data)-1]["Adj Close"]
    data = data.rename(columns = {"Adj Close": "Adj_Close"})
    data['pct_change'] = data.Adj_Close.pct_change(1)
    data['log_return'] = np.log(data.Adj_Close / data.Adj_Close.shift(1))
    df2 = pd.concat([data['pct_change'], data['log_return']], axis = 1)
    df2 = df2.reset_index(level=['Date'])
    df2 = df2.drop(columns = ['Date'])
    df2.reset_index(level=0, inplace=True)
    df2 = df2.dropna()
    return S0,df2

"""## Random Generators"""

import os
import binascii


def GetRandomIndex (x,seed=None):
    seed = (
        seed if seed is not None
        else int(binascii.hexlify(os.urandom(4)), 16))
    rs = np.random.RandomState(seed)
    return rs.randint(x)

def GetExpon(y=1):
  return np.random.exponential(scale=y,size=None)

def FlipCoin(x=[-1,1]):
  return np.random.choice(x,None,[0.5,0.5])

def FlipExpon(y=0.1,x=[-1,1]):
  return GetExpon(y)*FlipCoin(x)

def GetRandomFlip(list1,ch=[0.9,0.1],seed=None):
  seed = (
        seed if seed is not None
        else int(binascii.hexlify(os.urandom(4)), 16))
  rs = np.random.RandomState(seed)
  return rs.choice(list1,None,p=ch)

def GetRandomNormal(mu, std , seed =None):
  seed = (
        seed if seed is not None
        else int(binascii.hexlify(os.urandom(4)), 16))
  rs = np.random.RandomState(seed)
  return rs.normal(mu, std, None)

import scipy
from scipy.stats import cauchy
from scipy.stats import t

def GetRandomCauchy(data):
  params = scipy.stats.cauchy.fit(data)
  arg = params[:-2]
  loc = params[-2]
  scale = params[-1]
  return loc, scale
  #return scipy.stats.cauchy.rvs(loc, scale)

def GetRandomDist_t(data):
  paramst = t.fit(data)
  deg_f = paramst[0]
  tloc = paramst[-2]
  tscale = paramst[-1]
  return deg_f , tloc , tscale
  #return scipy.stats.t.rvs(deg_f, loc=tloc, scale=tscale)

"""##Spark UDFs

### Historical Dictionary
"""

def GetDict(a):
  return b.value.get(a)

"""### Simple Case"""

def f(y):
    lsum=0.0
    for _ in range(y):
      a=GetRandomIndex(len(b.value))
      v=GetDict(a)
      if v is None:
        lsum += 0.0
      else:
        lsum += v
    return lsum

def historical_dict():
  return udf(lambda c: f(c),FloatType())

"""### Flip Coin - Chance for Exponential"""

def f_expon(y,ch=[0.9,0.1]):
  lsum =0.0
  for _ in range(y):
    coin=GetRandomFlip(["GetRandomIndex","FlipExpon"],ch)
    if coin =='GetRandomIndex':
      a=GetRandomIndex(len(b.value))
      v=GetDict(a)
      if v is None:
        lsum += 0.0
      else:
        lsum += v
      #sum=sum*(1+df_index.filter(data.id==GetRandomIndex(data.count())).select("pct_change").collect()[0][0])
    else:
      lsum += FlipExpon()
      #sum=sum*(1+FlipExpon())
  return lsum

def simple_expon():
  return udf(lambda c: f_expon(c,ch=[0.9,0.1]),FloatType())

"""### Flip Coin - Chance for Cauchy"""

def f_cauchy(y,ch=[0.9,0.1]):
  lsum =0.0
  for _ in range(y):
    coin=GetRandomFlip(["GetRandomIndex","Cauchy"],ch)
    if coin =='GetRandomIndex':
      a=GetRandomIndex(len(b.value))
      v=GetDict(a)
      if v is None:
        lsum += 0.0
      else:
        lsum += v
      #sum=sum*(1+df_index.filter(data.id==GetRandomIndex(data.count())).select("pct_change").collect()[0][0])
    else:
      lsum += scipy.stats.cauchy.rvs(b_loc, b_scale)
      #sum=sum*(1+FlipExpon())
  return lsum

def simple_cauchy():
  return udf(lambda c: f_cauchy(c,ch=[0.9,0.1]),FloatType())

"""### Flip Coin - Chance for T"""

def f_t(y,ch=[0.9,0.1]):
  lsum =0.0
  for _ in range(y):
    coin=GetRandomFlip(["GetRandomIndex","T"],ch)
    if coin =='GetRandomIndex':
      a=GetRandomIndex(len(b.value))
      v=GetDict(a)
      if v is None:
        lsum += 0.0
      else:
        lsum += v
      #sum=sum*(1+df_index.filter(data.id==GetRandomIndex(data.count())).select("pct_change").collect()[0][0])
    else:
      lsum += scipy.stats.t.rvs(b_deg_f, loc=b_tloc, scale=b_tscale)
      #sum=sum*(1+FlipExpon())
  return lsum

def simple_t():
  return udf(lambda c: f_t(c,ch=[0.9,0.1]),FloatType())

"""### Simple Window"""

def f_window(y):
  lsum =0.0
  a=GetRandomIndex(len(b.value))
  v=GetDict(a)
  l= len(b.value)
  if v is None:
    lsum += 0.0
  else:
    lsum += v
  for i in range(y-1):
    v=GetDict((a+i)%l)
    if v is None:
      lsum += 0.0
    else:
      lsum += v
  return lsum

def simple_window():
  return udf(lambda c: f_window(c),FloatType())

"""### 10 day Window"""

def f_tenwindow(y):
  lsum =0.0
  a=GetRandomIndex(len(b.value))
  v=GetDict(a)
  l= len(b.value)
  if v is None:
    lsum += 0.0
  else:
    lsum += v
  for i in range(y-1):
    v=GetDict((a+10*i)%l)
    if v is None:
      lsum += 0.0
    else:
      lsum += v
  return lsum

def ten_window():
  return udf(lambda c: f_tenwindow(c),FloatType())

"""### 20 day Window"""

def f_twentywindow(y):
  lsum =0.0
  a=GetRandomIndex(len(b.value))
  v=GetDict(a)
  l= len(b.value)
  if v is None:
    lsum += 0.0
  else:
    lsum += v
  for i in range(y-1):
    v=GetDict((a+20*i)%l)
    if v is None:
      lsum += 0.0
    else:
      lsum += v
  return lsum

def twenty_window():
  return udf(lambda c: f_twentywindow(c),FloatType())

"""# Main"""

spark = SparkSession.builder.master('local[*]').appName("SP_2").getOrCreate()
spark.conf.set("spark.sql.execution.arrow.enabled", "true")

"""##Download Data from Yfinance and EDA"""

symbol = '^GSPC'
S0,df_input = GetYFinanceData (symbol)

log_array = df_input[['log_return']].to_numpy()

mu =np.mean(log_array)

std =np.std(log_array)

loc, scale = GetRandomCauchy(log_array)

deg_f , tloc , tscale = GetRandomDist_t(log_array)

mu, std, loc, scale, deg_f, tloc, tscale

"""## Intermediate DFs and dictionaries"""

sdf = spark.createDataFrame(df_input)
df_index = sdf.select(['pct_change','log_return']).withColumn("id",
		   F.row_number().over(Window.orderBy(F.monotonically_increasing_id()))
     )

new_dict1 = df_index.toPandas()
new_dict2 = new_dict1.drop(columns = 'pct_change')
dict_ret = new_dict2.set_index('id')['log_return'].dropna().to_dict()

res = None in dict_ret.values()
print("Does Dictionary contain None value ? " + str(res))

len(dict_ret.items())

from itertools import product

listRuns = [1000]
a = (S0//10)*10
listK = [a]
T1 = 10
listT = [T1]
result = list(product(listK, listT, listRuns))
Intermediate_Target_df = pd.DataFrame(result, columns =['K', 'T', 'Runs'])
Intermediate_Target_df.tail()

r = 0.01
schema = StructType([
    StructField("K", FloatType(), False), StructField("T", IntegerType(), False), StructField("Runs", IntegerType(), False)
])
df = spark.createDataFrame(Intermediate_Target_df, schema)
df.printSchema()

l_ind=[]
for i in range(len(listRuns)):
  for j in range(1,listRuns[i]+1):
    l_ind.append([listRuns[i],j])

dfRuns=pd.DataFrame(l_ind,columns =[ 'Runs','No'])

schemaRuns = StructType([
     StructField("Runs", IntegerType(), False),StructField("No", IntegerType(), False)
])
dfR=spark.createDataFrame(dfRuns, schemaRuns)
dfR.printSchema()

target_df = df.join(dfR, on='Runs', how='inner')
target_df.printSchema()

target_df.select('*').show(10)

b= spark.sparkContext.broadcast(dict_ret)
len(b.value)

b_deg_f = spark.sparkContext.broadcast(deg_f)
b_tloc = spark.sparkContext.broadcast(tloc)
b_tscale = spark.sparkContext.broadcast(tscale)
b_loc = spark.sparkContext.broadcast(loc)
b_scale = spark.sparkContext.broadcast(scale)
b_mu = spark.sparkContext.broadcast(mu)
b_std = spark.sparkContext.broadcast(std)

"""## Result Dataframes

### Simple Case
"""

dfRes = target_df.select('*').withColumn("logsum",historical_dict()(F.col('T'))).withColumn("sum",lit(S0)*F.exp("logsum")).withColumn("priceCall",expr("""IF(sum>K,sum-K,0.0) """)).withColumn("pricePut",expr("""IF(sum<K,K-sum,0.0) """))

"""### Simple Window"""

dfS_W = target_df.select('*').withColumn("logsum",simple_window()(F.col('T'))).withColumn("sum",lit(S0)*F.exp("logsum")).withColumn("priceCall",expr("""IF(sum>K,sum-K,0.0) """)).withColumn("pricePut",expr("""IF(sum<K,K-sum,0.0) """))

"""### 10 day window"""

dfS_10W = target_df.select('*').withColumn("logsum",ten_window()(F.col('T'))).withColumn("sum",lit(S0)*F.exp("logsum")).withColumn("priceCall",expr("""IF(sum>K,sum-K,0.0) """)).withColumn("pricePut",expr("""IF(sum<K,K-sum,0.0) """))

"""### 20 day window"""

dfS_20W = target_df.select('*').withColumn("logsum",twenty_window()(F.col('T'))).withColumn("sum",lit(S0)*F.exp("logsum")).withColumn("priceCall",expr("""IF(sum>K,sum-K,0.0) """)).withColumn("pricePut",expr("""IF(sum<K,K-sum,0.0) """))

"""###Exponential"""

dfSexp = target_df.select('*').withColumn("logsum",simple_expon()(F.col('T'))).withColumn("sum",lit(S0)*F.exp("logsum")).withColumn("priceCall",expr("""IF(sum>K,sum-K,0.0) """)).withColumn("pricePut",expr("""IF(sum<K,K-sum,0.0) """))

"""### Cauchy"""

dfScauchy = target_df.select('*').withColumn("logsum",simple_cauchy()(F.col('T'))).withColumn("sum",lit(S0)*F.exp("logsum")).withColumn("priceCall",expr("""IF(sum>K,sum-K,0.0) """)).withColumn("pricePut",expr("""IF(sum<K,K-sum,0.0) """))

"""### T"""

dfS_t = target_df.select('*').withColumn("logsum",simple_t()(F.col('T'))).withColumn("sum",lit(S0)*F.exp("logsum")).withColumn("priceCall",expr("""IF(sum>K,sum-K,0.0) """)).withColumn("pricePut",expr("""IF(sum<K,K-sum,0.0) """))

"""## Aggregate Dataframes and Writing to Output"""

dfRes.groupBy("Runs","K","T").agg(avg("priceCall").alias('CallPrice'),avg("pricePut").alias("PutPrice")).show()

"""## Random Functions Playground"""

params = scipy.stats.cauchy.fit(log_array)
params

arg = params[:-2]
loc = params[-2]
scale = params[-1]

scipy.stats.cauchy.rvs(loc, scale)

#mean, var = t.fit(data)
paramst = t.fit(log_array)
deg_f = paramst[0]
tloc = paramst[-2]
tscale = paramst[-1]

deg_f , tloc , tscale

t.rvs(deg_f, loc=tloc, scale=tscale)

a = GetRandomFlip(['hist','rand'])
a

"""## End of Spark"""

spark.stop()